image: node:lts

stages:
  - build

  - test

  - deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

cache:
  - key:
      files:
        - package-lock.json

    paths:
      - node_modules/

install:
  stage: build

  script:
    - npm install

  artifacts:
    paths:
      - node_modules/

prettier:
  stage: test

  script:
    - npm run prettier

  allow_failure: false

lint:
  stage: test

  script:
    - npm run lint

  allow_failure: false
